### ISSUE TITLE
[Fix] Share extension 오류 해결

### ISSUE THREAD

**Issue by haneulKimaa** [TeamPhotoSurfer/PhotoSurfer-iOS#160]
## Issue

Share extension 오류 해결
## To-do

- [x] Share extension 태그 입력 후 search bar 지워지지 않는 오류  
- [x] 태그 저장 lottie 뜨지 않는 오류
- [x] 알림탭 x 버튼 클릭시 공유 끝냄
