### ISSUE TITLE
[Feat] share extension 세부 기능 구현

### ISSUE THREAD

**Issue by haneulKimaa** [TeamPhotoSurfer/PhotoSurfer-iOS#29]
## Issue

share extension 세부 기능 구현

## To-do

- [x] 입력 중인 데이터 보여주는 로직 오류 해결
- [x] share extension 태그 클릭 기능 구현
- [x] 연관 태그 상세 기능 구현
- [x] 태그 길이 오류 수정
