### ISSUE TITLE
[Style] 설정 화면 구성

### ISSUE THREAD

**Issue by jeongkite** [TeamPhotoSurfer/PhotoSurfer-iOS#33]
## Issue

설정 화면을 구성합니다.

## To-do

- [x] 설정 메인 구성
- [x] 계정 관리 구성
- [x] 기타 정책 구성
