### ISSUE TITLE
[Fix] Share Extension 태그 검색 뷰 로직 수정

### ISSUE THREAD

**Issue by haneulKimaa** [TeamPhotoSurfer/PhotoSurfer-iOS#56]
## Issue

Share Extension 태그 검색 뷰 로직 오류 수정

## To-do

- [ ] 깜빡임 오류 수정
- [x] 화면 클릭 이벤트 오류 수정
- [x] 실시간 입력 라벨 위치 이동 구현
